### ISSUE TITLE
Error building on Xcode 6.1 on MacOS 10.10.4

### ISSUE THREAD

**Issue by oscarbg** [UoB-HPC/GPU-STREAM#2] opened 2015-09-06 13:24 UTC
Hi,
using that configuration I get:
In file included from ocl-stream.cpp:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:626:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:253:9: **error**: 
      field has incomplete type 'cl::Device'
    _T1 first;

I will update Xcode to see if it fixes the issue..

**Comment by jrprice** [comment] 2015-09-06 15:48
I couldn't reproduce this with Xcode 6.4, on OS X 10.10.5.

**Comment by tomdeakin** [comment] 2015-09-21 14:43
Any updates on this issue?

**Comment by tomdeakin** [comment] 2016-02-25 20:53
Closing issue as OS X 10.11 and Xcode 7 have been released and we cannot replicate the issue.

**Closed by tomdeakin** 2016-02-25 20:53 UTC
